"""Compatibility wrapper for the caldera environment module."""

try:
    from .caldera_env import (
        ACTION_NAMES,
        ACTION_TO_INDEX,
        CalderaEnv,
        DEFAULT_PIT_PARAMS,
        DEFAULT_PIT_WEIGHTS,
        DEFAULT_VALUE,
        DIRECTION_STEPS,
        MOVE_EAST,
        MOVE_NORTH,
        MOVE_SOUTH,
        MOVE_WEST,
        MOVEMENT_ACTIONS,
        SAMPLE,
        WRONG_TURN_ACTION,
        reward_function_explore,
        stochastic_effet_none,
        stochastic_effet_wrong_turn,
    )
except ImportError:
    from caldera_env import (
        ACTION_NAMES,
        ACTION_TO_INDEX,
        CalderaEnv,
        DEFAULT_PIT_PARAMS,
        DEFAULT_PIT_WEIGHTS,
        DEFAULT_VALUE,
        DIRECTION_STEPS,
        MOVE_EAST,
        MOVE_NORTH,
        MOVE_SOUTH,
        MOVE_WEST,
        MOVEMENT_ACTIONS,
        SAMPLE,
        WRONG_TURN_ACTION,
        reward_function_explore,
        stochastic_effet_none,
        stochastic_effet_wrong_turn,
    )

__all__ = [
    "ACTION_NAMES",
    "ACTION_TO_INDEX",
    "CalderaEnv",
    "DEFAULT_PIT_PARAMS",
    "DEFAULT_PIT_WEIGHTS",
    "DEFAULT_VALUE",
    "DIRECTION_STEPS",
    "MOVE_EAST",
    "MOVE_NORTH",
    "MOVE_SOUTH",
    "MOVE_WEST",
    "MOVEMENT_ACTIONS",
    "SAMPLE",
    "WRONG_TURN_ACTION",
    "reward_function_explore",
    "stochastic_effet_none",
    "stochastic_effet_wrong_turn",
]
