name: parlai-alt
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - pandas
  - matplotlib
  - tqdm
  - gymnasium
  - scikit-learn
  - pytorch
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - unified-planning[fast-downward]
