name: parlai-tut
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - jupyterlab-slideshow
  - ipywidgets
  - ipykernel
  - matplotlib
  - mediapy
  - ffmpeg
  - tqdm
  - gymnasium
  - gymnasium-classic_control
  - gymnasium-box2d
  - gymnasium-toy_text
  - pip
  - pytorch
  - pip:
      - pddlgym
      - gymcts
      - unified-planning[fast-downward]
      - git+https://github.com/guyazran/jupyter-timeout
